/*
 * This source file was generated by the Gradle 'init' task
 */
package com.lament.z.bitmagic;

public class BitMagic {
    public String getGreeting() {
        return "Hello，This project contains some bit trick demos.";
    }

    public static void main(String[] args) {
        System.out.println(new BitMagic().getGreeting());
    }
}
